# Generated by Django 4.1.7 on 2023-05-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrawData1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_ts', models.CharField(blank=True, max_length=20, null=True)),
                ('material_vs', models.CharField(blank=True, max_length=20, null=True)),
                ('carbon', models.CharField(blank=True, max_length=20, null=True)),
                ('hydrogen', models.CharField(blank=True, max_length=20, null=True)),
                ('nitrogen', models.CharField(blank=True, max_length=20, null=True)),
                ('is_add', models.IntegerField(blank=True, null=True)),
                ('is_pre', models.IntegerField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('ch4', models.CharField(blank=True, max_length=30, null=True)),
                ('gas', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'straw_data1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StrawData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_ts', models.CharField(blank=True, max_length=20, null=True)),
                ('material_vs', models.CharField(blank=True, max_length=20, null=True)),
                ('is_add', models.IntegerField(blank=True, null=True)),
                ('is_pre', models.IntegerField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('ch4', models.CharField(blank=True, max_length=30, null=True)),
                ('gas', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'straw_data2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StrawData3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_ts', models.CharField(blank=True, max_length=20, null=True)),
                ('material_vs', models.CharField(blank=True, max_length=20, null=True)),
                ('carbon', models.CharField(blank=True, max_length=20, null=True)),
                ('hydrogen', models.CharField(blank=True, max_length=20, null=True)),
                ('oxygen', models.CharField(blank=True, max_length=20, null=True)),
                ('nitrogen', models.CharField(blank=True, max_length=20, null=True)),
                ('is_add', models.IntegerField(blank=True, null=True)),
                ('is_pre', models.IntegerField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('ch4', models.CharField(blank=True, max_length=30, null=True)),
                ('gas', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'straw_data3',
                'managed': False,
            },
        ),
    ]
